main_front
SUVID-18/tag_management pull request #19
Opened 2023-04-09 12:21 UTC by Planybirth

태그 관리 앱의 태그 등록 페이지, 로그인 화면, 태그 정보 관리 페이지 구현 - 프론트엔드 작업 완료

2023-04-09 12:48 UTC, 000hgf requested changes
머터리얼 앱만 수정해주세용

2023-04-09 12:48 UTC, sun30812 requested changes
코드상에 수정 사항이 많습니다.

특히 `MaterialApp()` 중첩 문제가 많습니다.

2023-04-09 12:48 UTC, sun30812 commented on lib/view/main_page.dart
> +  static const String _title = 'Flutter Code Sample';
불필요한 코드(앱 이름??)

2023-04-09 12:48 UTC, sun30812 commented on lib/view/main_page.dart
> +    return const MaterialApp(
중복된 함수 사용(MaterialApp)

2023-04-09 12:48 UTC, sun30812 commented on lib/view/main_page.dart
> +    return MaterialApp(
중복된 함수 사용(MaterialApp)

2023-04-09 12:48 UTC, sun30812 commented on lib/view/management.dart
> +    return MaterialApp(
중복된 함수 사용(MaterialApp)

2023-04-09 12:48 UTC, sun30812 commented on lib/view/management.dart
> +  void _showEditDialog(int index) {
주석이 필요합니다.

2023-04-09 12:48 UTC, sun30812 commented on lib/view/management.dart
>      return const Placeholder();
?

2023-04-09 12:55 UTC, dongminii approved these changes

2023-04-09 13:01 UTC, dongminii approved these changes

2023-04-11 15:37 UTC, Planybirth commented on lib/view/main_page.dart
> +    return MaterialApp(
MaterialApp 제거완료.

2023-04-11 15:38 UTC, Planybirth commented on lib/view/main_page.dart
> +    return const MaterialApp(
MaterialApp 제거완료.

2023-04-11 15:38 UTC, Planybirth commented on lib/view/management.dart
>      return const Placeholder();
불필요한 함수 제거완료.

2023-04-11 15:38 UTC, Planybirth commented on lib/view/management.dart
> +    return MaterialApp(
MaterialApp 제거완료.

2023-04-11 15:38 UTC, Planybirth commented on lib/view/management.dart
> +  void _showEditDialog(int index) {
추가 주석을 달았습니다.

2023-04-11 15:43 UTC, Planybirth commented on lib/view/main_page.dart
> +  static const String _title = 'Flutter Code Sample';
_title 삭제 완료.

2023-04-11 15:45 UTC, sun30812 approved these changes
변경사항 확인했습니다.

2023-04-12 06:19 UTC, 000hgf approved these changes
확인했습니다

2023-04-12 06:22 UTC, merged